package com.taskmanager.mcp.tools;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Service;

@Service
public class SchemaTools {

    @Tool(name = "mcp-schema-tasks", description = "Returns the database schema for the tasks table as a simplified JSON Schema. Use this to understand the structure before inserting data.")
    public String getTaskSchema() {
        return """
                {
                  "table": "tasks",
                  "columns": {
                    "id": {
                      "type": "bigint",
                      "primaryKey": true,
                      "autoGenerated": true,
                      "description": "Auto-generated unique identifier"
                    },
                    "title": {
                      "type": "varchar(100)",
                      "required": true,
                      "description": "Task title, max 100 characters"
                    },
                    "description": {
                      "type": "varchar(500)",
                      "required": false,
                      "description": "Optional task description, max 500 characters"
                    },
                    "status": {
                      "type": "varchar(20)",
                      "required": true,
                      "enum": ["TODO", "IN_PROGRESS", "DONE"],
                      "default": "TODO",
                      "description": "Task status"
                    },
                    "dueDate": {
                      "type": "date",
                      "required": false,
                      "format": "yyyy-MM-dd",
                      "description": "Optional due date in ISO format"
                    }
                  }
                }
                """;
    }
}
